sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 8
services: docker
before_install:
  - cd 19_RestWithASPNETErudio_AddingDockerSupport/RestWithASPNETErudio
  - echo "We are in the right folder!"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag rest-with-asp-net-erudio:latest $DOCKER_USERNAME/rest-with-asp-net-erudio:$TRAVIS_JOB_ID;
    docker tag rest-with-asp-net-erudio-db:latest $DOCKER_USERNAME/rest-with-asp-net-erudio-db:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-with-asp-net-erudio:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-with-asp-net-erudio-db:$TRAVIS_JOB_ID;
  on:
    branch: master
notifications:
  email: false
