version: '3.4'

services:
  db:
    image: rest-with-asp-net-erudio-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_erudio
    ports:
      - 3308:3306
    networks:
      - erudio-network
      
  rest-with-asp-net-erudio:
    image: rest-with-asp-net-erudio
    build:
      context: .
      dockerfile: RestWithASPNETErudio/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    depends_on:
      - db
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge
    
